class Commands:
    LEECH = "leech@uploadinghb4allbot"
    PURGE = "purge"
    PAUSEALL = "pauseall"
    RESUMEALL = "resumeall"
    STATUS = "status@uploadinghb4allbot"
    SETTINGS = "settings"
    EXEC = "exec"
    UPLOAD = "upload"
    YTDL = "ytdl@uploadinghb4allbot"
    PYTDL = "pytdl@uploadinghb4allbot"
    ABOUT = "about"
    GETLOGS = "getlogs"
    SERVER = "server"
    USERSETTINGS = "usetting"
    INSTADL = "instadl@uploadinghb4allbot"
