class Commands:
    LEECH = "leech@uploadinghb4allbot"
    PURGE = "purge"
    PAUSEALL = "pauseall@uploadinghb4allbot"
    RESUMEALL = "resumeall@uploadinghb4allbot"
    STATUS = "status@uploadinghb4allbot"
    SETTINGS = "settings@uploadinghb4allbot"
    EXEC = "exec@uploadinghb4allbot"
    UPLOAD = "upload@uploadinghb4allbot"
    YTDL = "ytdl@uploadinghb4allbot"
    PYTDL = "pytdl@uploadinghb4allbot"
    ABOUT = "about@uploadinghb4allbot"
    GETLOGS = "getlogs@uploadinghb4allbot"
    SERVER = "server@uploadinghb4allbot"
    USERSETTINGS = "usetting@uploadinghb4allbot"
    INSTADL = "instadl@uploadinghb4allbot"
